clone_depth: 1

init:
- git config --global core.autocrlf true

build_script:
- msbuild "SqlPad.sln" /verbosity:minimal /p:DefineConstants="ORACLE_MANAGED_DATA_ACCESS_CLIENT" /p:Configuration=Release /p:Platform="x86" /verbosity:normal

artifacts:
- path: TestResult.xml
